# Generated by Django 5.2.6 on 2025-09-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_tbl',
            name='user_type',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
