# Generated by Django 5.2.6 on 2025-09-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_online', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_Tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
