# Generated by Django 5.2.6 on 2025-09-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_online', '0002_alter_reg_tbl_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_Tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_image', models.FileField(upload_to='pictures')),
                ('item_description', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size_chart', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=5)),
                ('color', models.CharField(max_length=50)),
                ('available_from', models.DateField(help_text='Available start date')),
                ('available_to', models.DateField(help_text='Available end date')),
            ],
        ),
    ]
