# Generated by Django 5.2.6 on 2025-09-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_online', '0003_product_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_Tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('prod_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_online.reg_tbl')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_online.product_tbl')),
            ],
        ),
    ]
