# Generated by Django 5.2.6 on 2025-09-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_online', '0004_cart_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_tbl',
            old_name='prod_name',
            new_name='u_name',
        ),
        migrations.CreateModel(
            name='Order_Tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_online.product_tbl')),
            ],
        ),
    ]
