# Generated by Django 5.2.6 on 2025-09-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_online', '0002_login_tbl'),
        ('rental_online', '0005_rename_prod_name_cart_tbl_u_name_order_tbl'),
    ]

    operations = [
    ]
