# Generated by Django 5.2.6 on 2025-09-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_online', '0006_merge_20250904_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tbl',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
